# -*- coding: utf-8 -*-
"""Matplotlib_and_Seaborn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gZI6Eqxh6khGqq1i54to9SsuMFSv3ayu
"""

!gdown https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/021/299/original/final_vg1_-_final_vg_%281%29.csv?1670840166 -O final_vg.csv

import pandas as pd
import numpy as np

data = pd.read_csv('final_vg.csv')
data.head()

import matplotlib.pyplot as plt

x_val=[0,1,2]
y_val=[3,5,9]

plt.plot(x_val, y_val)

cat_count= data['Genre'].value_counts()

cat_count

cat_count.index



x_bar= cat_count.index
y_bar= cat_count
plt.bar(x_bar, y_bar)

plt.figure(figsize=(12,8))
plt.bar(x_bar, y_bar)

#rotate the x labels
plt.figure(figsize=(12,8))
plt.bar(x_bar, y_bar)
plt.xticks(rotation=90, fontsize=12)

#Change the width of these bars
plt.figure(figsize=(12,8))
plt.bar(x_bar, y_bar, width=0.2)
plt.xticks(rotation=90, fontsize=12)

plt.figure(figsize=(12,8))
plt.bar(x_bar, y_bar, width=0.2, color='orange')
plt.xticks(rotation=90, fontsize=12)
plt.title("Games per Genre", fontsize= 15)
plt.xlabel("Genre")
plt.ylabel("Count of Games")

plt.figure(figsize=(12,8))
plt.bar(x_bar, y_bar, width=0.2, color='orange')
plt.xticks(rotation=90, fontsize=12)
plt.title("Games per Genre", fontsize= 15)
plt.xlabel("Genre")
plt.ylabel("Count of Games")
plt.show()

x=20
y=30

x
y

y

import seaborn as sbn

sbn.countplot(x='Genre', data =data , order= cat_count.index)
plt.show()

#pie chart

sales_data=data[["NA_Sales","EU_Sales","JP_Sales","Other_Sales"]]

sales_data

sales_data.T

regional_sale= sales_data.T.sum(axis='columns')

regional_sale

plt.pie(regional_sale, labels=regional_sale.index, autopct='%.2f%%' )

plt.pie(regional_sale, labels=regional_sale.index, autopct='%.2f%%', explode= (0,0.5,0,0) )
plt.show()

#histograms

plt.hist(data['Year'])
plt.show()

#popularity of games year on year

plt.hist(data['Year'], bins= 50)
plt.show()

#seaborn library

sbn.histplot(data['Year'])

sbn.histplot(data['Year'], bins=10)

sbn.kdeplot(data['Year']) #more smoothened version of histogram, more interpretable

data.describe()

data['NA_Sales'].describe()

plt .figure(figsize=(12,10))
sbn.boxplot(y=data['NA_Sales'])
plt.ylabel("North America Sales")
plt.yticks(fontsize=20)

